import { Product, Category, Deal, AppConfig } from './types';

export const INITIAL_CONFIG: AppConfig = {
  businessName: "Dehli Mutton & Beef",
  businessNameUr: "دہلی مٹن اینڈ بیف",
  tagline: "Fresh Daily | Halal | Quality Meat",
  taglineUr: "روزانہ تازہ | حلال | معیاری گوشت",
  whatsappNumber: "+923128535399",
  email: "dehlimuttonandbeef@gmail.com",
  phone: "0312 8535 399",
  address: "18/E, sunset lane 3, phase 2, DHA karachi.pakistan",
  addressUr: "18/E، سن سیٹ لین 3، فیز 2، ڈی ایچ اے کراچی، پاکستان",
  minOrderMutton: 3,
  currency: "₨",
  bankName: "Meezan Bank",
  accountNumber: "1234-5678-9012-3456",
  accountTitle: "Dehli Mutton & Beef Center",
  botInstruction: "You are the official AI Assistant for Dehli Mutton & Beef. Reply in Roman Urdu + English. Help with recipes like Karahi, Qorma, Biryani. Suggest best meat cuts for specific cooking methods: Grilling/BBQ (Chops, Ribs), Roasting (Raan, Shoulder), Stewing/Gravy (Neck, Bone-in), and Quick Cooking (Qeema, Chicken). Give health tips (e.g. Chicken for sick people). Be concise and friendly. If the user language is Urdu, please respond primarily in Urdu script."
};

export const CATEGORIES: Category[] = [
  { id: 'mutton', name: 'Mutton', nameUr: 'مٹن', icon: 'Beef', image: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?q=80&w=500&auto=format&fit=crop' },
  { id: 'beef', name: 'Beef', nameUr: 'بیف', icon: 'Drumstick', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop' },
  { id: 'chicken', name: 'Chicken', nameUr: 'چکن', icon: 'Bird', image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=500&auto=format&fit=crop' },
  { id: 'fish', name: 'Fish', nameUr: 'مچھلی', icon: 'Fish', image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?q=80&w=500&auto=format&fit=crop' },
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal1',
    title: 'Weekend Special',
    titleUr: 'ویک اینڈ اسپیشل',
    description: 'Get extra fat for free on 5kg Mutton purchase',
    descriptionUr: '5 کلو مٹن کی خریداری پر اضافی چربی مفت حاصل کریں',
    discount: 'Special',
    discountUr: 'خصوصی',
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6e9460272?q=80&w=1000&auto=format&fit=crop'
  },
  {
    id: 'deal2',
    title: 'Bulk Fish Order',
    titleUr: 'مچھلی کا بڑا آرڈر',
    description: 'Flat 10% off on wholesale fish orders above 20pcs',
    descriptionUr: '20 عدد سے زیادہ مچھلی کے ہول سیل آرڈر پر 10 فیصد رعایت',
    discount: '10% OFF',
    discountUr: '10% رعایت',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=1000&auto=format&fit=crop'
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  // Mutton
  { id: 'm1', name: 'Mutton Shoulder', nameUr: 'مٹن شانہ', description: 'Tender shoulder cut (Bone-in), ideal for slow cooking and stews.', descriptionUr: 'نرم شانہ (ہڈی کے ساتھ)، ہلکی آنچ پر پکانے اور سالن کے لیے بہترین۔', price: 3400, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=500&auto=format&fit=crop', tag: 'Bone-in', tagUr: 'ہڈی والا' },
  { id: 'm2', name: 'Mutton Leg', nameUr: 'مٹن ران', description: 'Whole leg of goat (Bone-in), perfect for slow roasting or BBQ.', descriptionUr: 'بکرے کی پوری ران (ہڈی کے ساتھ)، روسٹ یا باربی کیو کے لیے بہترین۔', price: 3500, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?q=80&w=500&auto=format&fit=crop', tag: 'Premium', tagUr: 'اعلیٰ' },
  { id: 'm3', name: 'Mutton Ribs', nameUr: 'مٹن پسلیاں', description: 'Meaty ribs (Bone-in) with rich flavor, great for curries.', descriptionUr: 'گوشت والی پسلیاں (ہڈی کے ساتھ)، مزیدار سالن کے لیے بہترین۔', price: 3100, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=500&auto=format&fit=crop' },
  { id: 'm4', name: 'Mutton Chops', nameUr: 'مٹن چاپ', description: 'Juicy chops (Bone-in), ideal for grilling or frying.', descriptionUr: 'رسیلی چاپیں (ہڈی کے ساتھ)، گرل یا فرائی کرنے کے لیے بہترین۔', price: 3300, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1602491453631-e2a5ad90a131?q=80&w=500&auto=format&fit=crop' },
  { id: 'm5', name: 'Mutton Loin', nameUr: 'مٹن لوئن', description: 'Premium loin cut (Boneless), very tender and lean.', descriptionUr: 'اعلیٰ معیار کا لوئن (بغیر ہڈی)، بہت نرم اور بغیر چربی والا۔', price: 3300, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1514472313571-33230a846c82?q=80&w=500&auto=format&fit=crop', tag: 'Boneless', tagUr: 'بغیر ہڈی' },
  { id: 'm6', name: 'Mutton Neck', nameUr: 'مٹن گردن', description: 'Bony neck pieces for rich gravies and soups.', descriptionUr: 'گردن کے ٹکڑے، گاڑھے سالن اور سوپ کے لیے۔', price: 3300, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1602491453631-e2a5ad90a131?q=80&w=500&auto=format&fit=crop' },
  { id: 'm7', name: 'Mutton Shank', nameUr: 'مٹن پنڈلی', description: 'Flavorsome shank meat (Bone-in), perfect for Nihari.', descriptionUr: 'ذائقہ دار پنڈلی کا گوشت (ہڈی کے ساتھ)، نہاری کے لیے بہترین۔', price: 3300, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=500&auto=format&fit=crop' },
  { id: 'm8', name: 'Mutton Breast', nameUr: 'مٹن سینہ', description: 'Meaty breast pieces (Bone-in) for various dishes.', descriptionUr: 'سینے کا گوشت (ہڈی کے ساتھ)، مختلف قسم کے کھانوں کے لیے۔', price: 3200, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1516684669134-de6f7c473a2a?q=80&w=500&auto=format&fit=crop' },
  { id: 'm9', name: 'Mutton Minced Meat', nameUr: 'مٹن قیمہ', description: 'Fine minced mutton (Boneless), prepared fresh.', descriptionUr: 'باریک کٹا ہوا تازہ مٹن قیمہ (بغیر ہڈی)۔', price: 3200, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1551028150-64b9f398f678?q=80&w=500&auto=format&fit=crop', tag: 'Boneless', tagUr: 'بغیر ہڈی' },
  { id: 'm10', name: 'Mutton Kunna', nameUr: 'مٹن کُنا', description: 'Special cut for authentic Kunna recipe.', descriptionUr: 'اصیل کُنا ترکیب کے لیے خاص گوشت۔', price: 3600, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=500&auto=format&fit=crop' },
  { id: 'm11', name: 'Mutton Biryani Cut', nameUr: 'مٹن بریانی کٹ', description: 'Perfect sized pieces for your special Biryani.', descriptionUr: 'آپ کی خاص بریانی کے لیے بہترین ٹکڑے۔', price: 3450, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=500&auto=format&fit=crop' },
  { id: 'm12', name: 'Mutton Qorma Cut', nameUr: 'مٹن قورمہ کٹ', description: 'Ideal cuts for rich and spicy Qorma.', descriptionUr: 'مزیدار اور چٹ پٹے قورمہ کے لیے بہترین کٹ۔', price: 3400, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=500&auto=format&fit=crop' },
  { id: 'm13', name: 'Mutton Karahi Cut', nameUr: 'مٹن کڑاہی کٹ', description: 'Fresh cuts perfect for Mutton Karahi.', descriptionUr: 'مٹن کڑاہی کے لیے تازہ اور بہترین ٹکڑے۔', price: 3300, unit: 'kg', unitUr: 'کلو', category: 'mutton', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=500&auto=format&fit=crop' },
  { id: 'm14', name: 'Whole Lamb', nameUr: 'ثابت دنبہ/بکرا', description: '12 kg net weight whole lamb for special occasions.', descriptionUr: 'خاص مواقع کے لیے 12 کلو نیٹ وزن کا ثابت بکرا۔', price: 41000, unit: 'pc', unitUr: 'عدد', category: 'mutton', image: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?q=80&w=500&auto=format&fit=crop', tag: 'Net 12kg', tagUr: '12 کلو' },
  
  // Beef
  { id: 'b1', name: 'Beef Chuck', nameUr: 'بیف چک', description: 'Flavorful chuck cut (Bone-in), great for slow cooking.', descriptionUr: 'ذائقہ دار چک گوشت (ہڈی کے ساتھ)، ہلکی آنچ پر پکانے کے لیے۔', price: 2100, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop', tag: 'Bone-in', tagUr: 'ہڈی والا' },
  { id: 'b2', name: 'Beef Rib', nameUr: 'بیف پسلیاں', description: 'Rich beef ribs (Bone-in) for BBQ or stews.', descriptionUr: 'بیف پسلیاں (ہڈی کے ساتھ)، باربی کیو یا سالن کے لیے۔', price: 2100, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?q=80&w=500&auto=format&fit=crop' },
  { id: 'b3', name: 'Beef Loin', nameUr: 'بیف لوئن', description: 'Tender loin cut (Boneless), ideal for steaks.', descriptionUr: 'نرم لوئن (بغیر ہڈی)، اسٹیک کے لیے بہترین۔', price: 2500, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1551028150-64b9f398f678?q=80&w=500&auto=format&fit=crop', tag: 'Boneless', tagUr: 'بغیر ہڈی' },
  { id: 'b4', name: 'Beef Round', nameUr: 'بیف راؤنڈ', description: 'Lean round cut (Boneless) for various beef dishes.', descriptionUr: 'بغیر چربی کا راؤنڈ گوشت (بغیر ہڈی)، مختلف کھانوں کے لیے۔', price: 2500, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=500&auto=format&fit=crop', tag: 'Boneless', tagUr: 'بغیر ہڈی' },
  { id: 'b5', name: 'Beef Brisket', nameUr: 'بیف برسکٹ', description: 'Perfect brisket (Bone-in/Mix) for slow-smoke BBQ or pot roast.', descriptionUr: 'باربی کیو یا پوٹ روسٹ کے لیے بہترین برسکٹ (ہڈی والا/مکس)۔', price: 2100, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1529692236671-f1f6e9460272?q=80&w=500&auto=format&fit=crop' },
  { id: 'b6', name: 'Beef Shank', nameUr: 'بیف پنڈلی', description: 'Traditional shank cut for Nihari and soups.', descriptionUr: 'نہاری اور سوپ کے لیے روایتی پنڈلی کا گوشت۔', price: 2200, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=500&auto=format&fit=crop' },
  { id: 'b7', name: 'Beef Plate', nameUr: 'بیف پلیٹ', description: 'Beef plate cut (Bone-in), flavorful and versatile.', descriptionUr: 'بیف پلیٹ گوشت (ہڈی کے ساتھ)، ذائقہ دار اور ورسٹائل۔', price: 2100, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?q=80&w=500&auto=format&fit=crop' },
  { id: 'b8', name: 'Beef Flank', nameUr: 'بیف فلینک', description: 'Lean flank cut (Boneless), great for quick cooking.', descriptionUr: 'بغیر چربی کا فلینک (بغیر ہڈی)، جلدی پکانے کے لیے بہترین۔', price: 2500, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop', tag: 'Boneless', tagUr: 'بغیر ہڈی' },
  { id: 'b9', name: 'Beef Biryani Cut', nameUr: 'بیف بریانی کٹ', description: 'Bone-in beef pieces specifically cut for Biryani.', descriptionUr: 'بریانی کے لیے خاص ہڈی والے بیف کے ٹکڑے۔', price: 2300, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop' },
  { id: 'b10', name: 'Beef Biryani Boneless', nameUr: 'بیف بریانی (بغیر ہڈی)', description: 'Boneless beef pieces for a luxury Biryani experience.', descriptionUr: 'اعلیٰ کوالٹی بریانی کے لیے بیف بریانی (بغیر ہڈی)۔', price: 2600, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop', tag: 'Boneless', tagUr: 'بغیر ہڈی' },
  { id: 'b11', name: 'Beef Undercut', nameUr: 'بیف انڈر کٹ', description: 'The most tender part of beef, perfect for steaks and kebabs.', descriptionUr: 'بیف کا سب سے نرم حصہ، اسٹیک اور کباب کے لیے بہترین۔', price: 3200, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop', tag: 'Super Tender', tagUr: 'انتہائی نرم' },
  { id: 'b12', name: 'Beef Trotters', nameUr: 'بیف پائے', description: 'Fresh beef trotters for a hearty soup.', descriptionUr: 'مزیدار شوربے کے لیے تازہ بیف پائے۔', price: 1700, unit: 'pc', unitUr: 'عدد', category: 'beef', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop' },
  { id: 'b13', name: 'Beef Brain', nameUr: 'بیف مغز', description: 'Fresh beef brain, delicacies for breakfast.', descriptionUr: 'تازہ بیف مغز، ناشتے کے لیے بہترین۔', price: 900, unit: 'pc', unitUr: 'عدد', category: 'beef', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop' },
  { id: 'b14', name: 'Beef Liver', nameUr: 'بیف کلیجی', description: 'Fresh and nutritious beef liver.', descriptionUr: 'تازہ اور غذائیت سے بھرپور بیف کلیجی۔', price: 1700, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop' },
  { id: 'b15', name: 'Beef Kidney', nameUr: 'بیف گردہ', description: 'Fresh beef kidney pieces.', descriptionUr: 'بیف کے تازہ گردے کے ٹکڑے۔', price: 600, unit: 'kg', unitUr: 'کلو', category: 'beef', image: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?q=80&w=500&auto=format&fit=crop' },
  
  // Chicken
  { id: 'c1', name: 'Whole Chicken', nameUr: 'ثابت چکن', description: 'Freshly dressed whole chicken for roasting.', descriptionUr: 'روسٹنگ کے لیے تازہ تیار شدہ ثابت چکن۔', price: 1200, unit: 'pc', unitUr: 'عدد', category: 'chicken', image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=500&auto=format&fit=crop' },
  { id: 'c2', name: 'Chicken Breast Boneless', nameUr: 'چکن بریسٹ (بغیر ہڈی)', description: 'Lean and versatile chicken breast boneless fillets.', descriptionUr: 'نرم اور بغیر ہڈی کا چکن بریسٹ فلے۔', price: 1300, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?q=80&w=500&auto=format&fit=crop', tag: 'Boneless', tagUr: 'بغیر ہڈی' },
  { id: 'c3', name: 'Chicken Wing', nameUr: 'چکن ونگز', description: 'Fresh chicken wings (Bone-in) for snacks and frying.', descriptionUr: 'تازہ چکن ونگز (ہڈی کے ساتھ)، اسنیکس اور فرائی کے لیے۔', price: 1000, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1527477396000-dcadcc662231?q=80&w=500&auto=format&fit=crop' },
  { id: 'c4', name: 'Chicken Leg Quarters', nameUr: 'چکن لیگ (کوارٹر)', description: 'Whole chicken leg quarter (Bone-in).', descriptionUr: 'چکن کا پورا لیگ کوارٹر (ہڈی کے ساتھ)۔', price: 1200, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?q=80&w=500&auto=format&fit=crop' },
  { id: 'c5', name: 'Chicken Thigh', nameUr: 'چکن ران (تھائی)', description: 'Juicy chicken thighs (Bone-in), great for BBQ.', descriptionUr: 'رسیلی چکن تھائی (ہڈی کے ساتھ)، باربی کیو کے لیے زبردست۔', price: 1300, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=500&auto=format&fit=crop' },
  { id: 'c6', name: 'Chicken Thigh Boneless', nameUr: 'چکن تھائی (بغیر ہڈی)', description: 'Tender boneless chicken thighs for better flavor.', descriptionUr: 'بہتر ذائقے کے لیے نرم چکن تھائی (بغیر ہڈی)۔', price: 1600, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=500&auto=format&fit=crop', tag: 'Boneless', tagUr: 'بغیر ہڈی' },
  { id: 'c7', name: 'Chicken Drumstick', nameUr: 'چکن ڈرم اسٹک', description: 'Popular drumstick cut for kids and BBQ.', descriptionUr: 'بچوں اور باربی کیو کے لیے پسندیدہ ڈرم اسٹک۔', price: 1200, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?q=80&w=500&auto=format&fit=crop' },
  { id: 'c8', name: 'Mix Chicken Meat', nameUr: 'مکس چکن گوشت', description: 'Standard mix pieces of chicken.', descriptionUr: 'چکن کے عام مکس ٹکڑے۔', price: 1100, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=500&auto=format&fit=crop' },
  { id: 'c9', name: 'Chicken Karahi Cut', nameUr: 'چکن کڑاہی کٹ', description: 'Perfectly sized pieces for Chicken Karahi.', descriptionUr: 'چکن کڑاہی کے لیے بہترین سائز کے ٹکڑے۔', price: 1100, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=500&auto=format&fit=crop' },
  { id: 'c10', name: 'Chicken Biryani Cut', nameUr: 'چکن بریانی کٹ', description: 'Ideal bone-in pieces for Chicken Biryani.', descriptionUr: 'چکن بریانی کے لیے بہترین ہڈی والے ٹکڑے۔', price: 1100, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=500&auto=format&fit=crop' },
  { id: 'c11', name: 'Chicken Neck', nameUr: 'چکن گردن', description: 'Bony chicken neck pieces.', descriptionUr: 'چکن کی گردن کے ٹکڑے۔', price: 1000, unit: 'kg', unitUr: 'کلو', category: 'chicken', image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?q=80&w=500&auto=format&fit=crop' },
  
  // Fish
  { id: 'f1', name: 'Whole Fish (Rohu)', nameUr: 'ثابت مچھلی (روہو)', description: 'Freshwater fish for wholesale.', descriptionUr: 'ہول سیل کے لیے تازہ مچھلی۔', price: 2500, unit: '10 pcs', unitUr: '10 عدد', category: 'fish', image: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?q=80&w=500&auto=format&fit=crop', wholesaleOnly: true },
  { id: 'f2', name: 'Fish Fillet', nameUr: 'فش فلے', description: 'Large scale clean fillets.', descriptionUr: 'صاف شدہ فلے۔', price: 5000, unit: '10 kg', unitUr: '10 کلو', category: 'fish', image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=500&auto=format&fit=crop', wholesaleOnly: true },
  { id: 'f3', name: 'Fish Steak', nameUr: 'فش اسٹیک', description: 'Standard cuts for bulk catering.', descriptionUr: 'بڑے آرڈرز کے لیے فش اسٹیک۔', price: 4500, unit: '10 kg', unitUr: '10 کلو', category: 'fish', image: 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?q=80&w=500&auto=format&fit=crop', wholesaleOnly: true },
];


export const TRANSLATIONS = {
  en: {
    home: "Home",
    categories: "Categories",
    cart: "Cart",
    contact: "Contact",
    addToCart: "Add to Cart",
    viewAll: "View All",
    orderWhatsApp: "Order on WhatsApp",
    total: "Total",
    totalPrice: "Total Price",
    search: "Search",
    since: "Since",
    guidelines: "Ordering Guidelines",
    minOrderMutton: "Mutton delivery: Minimum",
    fishBulk: "Fish: Bulk/Wholesale orders only",
    deals: "Today's Deals",
    all: "ALL",
    pricing: "Pricing",
    per: "PER",
    muttonNote: "Note: Minimum order for Mutton delivery is",
    callUs: "Call Us",
    emailUs: "Email Us",
    visitUs: "Visit Us",
    admin: "ADMIN",
    recipe: "Recipe Chahiye",
    meatSuggestion: "Gosht Suggestion",
    cookingMethods: "Cooking Methods",
    healthAdvice: "Health Advice",
    orderNow: "Order Karo",
    clearChat: "Clear Chat",
    assistant: "Chat Assistant",
    placeholder: "Ask something...",
    paymentMethod: "Payment Method",
    cash: "Cash on Delivery",
    onlineBanking: "Online Banking",
    bankDetails: "Bank Details",
    accountTitle: "Account Title",
    accountNumber: "Account Number",
    bankName: "Bank Name",
  },
  ur: {
    home: "ہوم",
    categories: "کیٹیگریز",
    cart: "کارٹ",
    contact: "رابطہ",
    addToCart: "کارٹ میں ڈالیں",
    viewAll: "سب دیکھیں",
    orderWhatsApp: "واٹس ایپ پر آرڈر کریں",
    total: "کل",
    totalPrice: "کل قیمت",
    search: "تلاش کریں",
    since: "سے",
    guidelines: "آرڈر کے قواعد",
    minOrderMutton: "مٹن ڈیلیوری: کم از کم",
    fishBulk: "مچھلی: صرف بلک / ہول سیل آرڈرز",
    deals: "آج کی ڈیلز",
    all: "سب",
    pricing: "قیمت",
    per: "فی",
    muttonNote: "نوٹ: مٹن ڈیلیوری کے لیے کم از کم آرڈر ہے",
    callUs: "ہمیں کال کریں",
    emailUs: "ای میل کریں",
    visitUs: "پتہ",
    admin: "ایڈمن",
    recipe: "ترکیب چاہیے",
    meatSuggestion: "گوشت کا مشورہ",
    cookingMethods: "پکانے کے طریقے",
    healthAdvice: "صحت کا مشورہ",
    orderNow: "آرڈر کریں",
    clearChat: "چیٹ صاف کریں",
    assistant: "چیٹ اسسٹنٹ",
    placeholder: "کچھ پوچھیں...",
    paymentMethod: "ادائیگی کا طریقہ",
    cash: "کیش آن ڈیلیوری",
    onlineBanking: "آن لائن بینکنگ",
    bankDetails: "بینک کی تفصیلات",
    accountTitle: "اکاؤنٹ کا عنوان",
    accountNumber: "اکاؤنٹ نمبر",
    bankName: "بینک کا نام",
  }
};
